name: BennyDB Unit Tests

on:
  push:
    paths:
      - 'bennyDB/**'
      - '.github/workflows/bennydb-test.yml'
  pull_request:
    paths:
      - 'bennyDB/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Create empty BennyDB.sqlite3
        working-directory: ./bennyDB
        run: |
          python -c "import sqlite3; sqlite3.connect('BennyDB.sqlite3').close()"

      - name: Run pytest
        working-directory: ./bennyDB
        run: |
          pytest -v test_bennyDB.py

      - name: Remove BennyDB.sqlite3
        if: always()  # ensures it runs even if tests fail
        working-directory: ./bennyDB
        run: rm -f BennyDB.sqlite3
